import os
import tempfile
import streamlit as st

from main import run_pipeline


st.set_page_config(
    page_title="Hybrid Phishing Detection System",
    page_icon="🛡️",
    layout="wide"
)
with st.sidebar:

    st.header("System Information")

    st.info(
        """
        Hybrid Architecture

        • Protocol Validation Layer
        • LLM Semantic Analysis
        • Risk Fusion Engine
        """
    )

    st.write("Model: Llama 3.1")
    st.write("Provider: OpenRouter")

st.title("🛡️ Hybrid Phishing Detection System")
st.write("LLM Semantic Analysis + Protocol Validation + Hybrid Fusion Engine")

uploaded_file = st.file_uploader(
    "Upload an email file (.eml)",
    type=["eml"]
)

if uploaded_file is not None:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".eml") as temp_file:
        temp_file.write(uploaded_file.read())
        temp_path = temp_file.name

    try:
        with st.spinner("Analyzing email..."):
            result = run_pipeline(temp_path)

        decision = result["decision"]

        st.subheader("Final Decision")

        col1, col2, col3 = st.columns(3)

        col1.metric("Prediction", "Phishing" if decision["is_phishing"] else "Legitimate")
        col2.metric("Risk Level", decision["risk"].upper())
        col3.metric("Score", decision["score"])
        st.progress(
            min(decision["score"] / 150, 1.0)
        )
        st.caption(
            f"Risk Score: {decision['score']} / 15"
        )

        if decision["is_phishing"]:
            st.error("🚨 PHISHING EMAIL DETECTED - HIGH RISK")
        else:
            st.success("This email is classified as legitimate.")

        st.subheader("System Workflow")
        col1, col2, col3 = st.columns(3)
        col1.success("Protocol Validation")
        col2.success("LLM Semantic Analysis")
        col3.success("Fusion Engine")
        
        st.subheader("Email Summary")
        st.write("**Subject:**", result["email"]["subject"])
        st.write("**Sender:**", result["email"]["sender"])
        st.write("**Semantic Source:**", result["semantic_source"])

        st.subheader("Reasons")
        st.write(
        "The final decision is generated by combining protocol validation evidence "
        "with semantic analysis performed by the Large Language Model."
        )

        for reason in decision["reasons"]:
            st.write("-", reason)

        if decision.get("recommended_action"):
            st.subheader("Recommended Action")
            st.info(decision["recommended_action"])

        st.subheader("Protocol Validation")
        sender = result["sender"]
        if sender["is_suspicious"]:
            st.warning("Suspicious sender detected.")
        else:
            st.success("Sender validation passed")
            st.write("### Sender Information")
            st.write("Sender Email:", sender["email"])
            st.write("Domain:", sender["domain"])

        for reason in sender["reasons"]:
            st.write("-", reason)
            st.write("---")
            st.write("### URL Analysis")

        for idx, url in enumerate(result["urls"], start=1):
            with st.expander(f"URL #{idx}"):
                st.write("**URL:**", url["url"])
                st.write("**Domain:**", url["domain"])

                if url["is_suspicious"]:
                    st.warning("Suspicious URL")
                else:
                    st.success("URL validation passed")

                for reason in url["reasons"]:
                    st.write("-", reason)
        st.write("---")
        if result["mismatch"]:
            st.error("Sender Domain Mismatch Detected")
        else:
            st.success("No Domain Mismatch Detected")
       

        st.subheader("LLM Semantic Analysis")
        semantic = result["semantic"]
        col1, col2 = st.columns(2)
        col1.metric(
        "Semantic Risk",
        str(semantic.get("risk", "unknown")).upper()
        )

        col2.metric(
        "Confidence",
        round(float(semantic.get("confidence", 0)), 2)
        )

        if semantic.get("social_engineering_indicators"):
            st.write("### Social Engineering Indicators")

        for item in semantic["social_engineering_indicators"]:
            st.write("-", item)
        if semantic.get("credential_theft_indicators"):
            st.write("### Credential Theft Indicators")

        for item in semantic["credential_theft_indicators"]:
            st.write("-", item)

        if semantic.get("impersonation_indicators"):
            st.write("### Impersonation Indicators")

        for item in semantic["impersonation_indicators"]:
            st.write("-", item)

        if semantic.get("reason"):
            st.write("### Analysis Summary")
            st.info(semantic["reason"])


    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)